-- CESTA DE 3
CREATE TABLE IF NOT EXISTS cestas_de_tres(
	id INT NOT NULL PRIMARY KEY,
    jogador VARCHAR(100) NOT NULL,
	qtd_pontos INT NOT NULL
);

-- TEMPO EM QUADRA
CREATE TABLE IF NOT EXISTS tempo_em_quadra(
	id INT NOT NULL PRIMARY KEY,
    jogador VARCHAR(100) NOT NULL,
	tempo FLOAT NOT NULL
);

-- JOGADOR QUE MAIS TEVE ASSISTENCIAS
CREATE TABLE IF NOT EXISTS assistencias(
	id INT NOT NULL PRIMARY KEY,
    jogador VARCHAR(100) NOT NULL,
    qtd_Assistencias INT NOT NULL
);

-- JOGADOR QUE MAIS PEGOU REBORES
CREATE TABLE IF NOT EXISTS rebotes(
	id INT NOT NULL PRIMARY KEY,
    jogador VARCHAR(100) NOT NULL,
    qtd_rebotes INT NOT NULL
);

-- JOGADOR QUE MAIS ROUBOU BOLAS
CREATE TABLE IF NOT EXISTS rebotes(
	id INT NOT NULL PRIMARY KEY,
    jogador VARCHAR(100) NOT NULL,
    qtd_rebotes INT NOT NULL
);

-- JOGADOR RECORDISTA EM TOCOS
CREATE TABLE IF NOT EXISTS tocos(
	id INT NOT NULL PRIMARY KEY,
    jogador VARCHAR(100) NOT NULL,
    qtd_tocos INT NOT NULL
);

-- RECORDISTA EM DUPLO-DUPLO
CREATE TABLE IF NOT EXISTS duplo_duplo(
	id INT NOT NULL PRIMARY KEY,
    jogador VARCHAR(100) NOT NULL,
    qtd_duplo_duplo INT NOT NULL
);

-- RECORDISTA EM TRIPLO-DUPLO
CREATE TABLE IF NOT EXISTS triplo_duplo(
	id INT NOT NULL PRIMARY KEY,
    jogador VARCHAR(100) NOT NULL,
    qtd_triplo_duplo INT NOT NULL
);

-- JOGADOR RECORDISTA EM FALTAS TECNICAS
CREATE TABLE IF NOT EXISTS faltas_tecnicas(
	id INT NOT NULL PRIMARY KEY,
    jogador VARCHAR(100) NOT NULL,
    qtd_faltas_tecnicas INT NOT NULL
);

-- JOGADOR MAIS VEZES SELECIONADO NO ALL STAR GAME
CREATE TABLE IF NOT EXISTS selecionado_allStar_game(
	id INT NOT NULL PRIMARY KEY,
    jogador VARCHAR(100) NOT NULL,
    qtd_selecionado INT NOT NULL
);



