-- MAIOR E MENOR PONTUAÇÃO DE UMA FRANQUIA EM UM JOGO NA NBA

CREATE TABLE IF NOT EXISTS maior_pontuacao(
	id INT NOT NULL PRIMARY KEY,
    franquia VARCHAR(50) NOT NULL,
	pontuacao VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS menor_pontuacao(
	id INT NOT NULL PRIMARY KEY,
    franquia VARCHAR(50) NOT NULL,
	pontuacao VARCHAR(100) NOT NULL
);

